Remove impossible condition
DivanteLtd/vue-storefront pull request #4533
Opened 2020-06-11 08:39 UTC by TerrorSquad

### Related Issues

closes #4528

### Short Description and Why It's Useful
It will enable regeneration of auth token if that token is expired or deleted without the need to reload the page.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [X] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-06-27 11:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=4533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=4533) before we can accept your contribution.<br/><hr/>**Goran Ninkovic** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vue-storefront?pullRequest=4533) it.</sub>

2020-09-28 10:53 UTC, gibkigonzo commented on core/lib/sync/task.ts
>            if (isNaN(rootStore.state.userTokenInvalidateLock) || isUndefined(rootStore.state.userTokenInvalidateLock)) rootStore.state.userTokenInvalidateLock = 0
please remove those lines (77, 78). Invalidation should be fixed with those changes https://github.com/DivanteLtd/vue-storefront/pull/4882

2020-09-28 10:54 UTC, gibkigonzo requested changes
@TerrorSquad please check a comment and rebase to `hotfix/v1.12.3`

2020-09-30 09:15 UTC, TerrorSquad commented
@gibkigonzo I updated the code. Can you review?

2020-09-30 09:28 UTC, gibkigonzo approved these changes

2020-09-30 09:49 UTC, Fifciu approved these changes

2020-09-30 13:44 UTC, TerrorSquad commented
Guys, for some reason, the licence still says Pending. I accepted it multiple times, but nothing changed here. Any ideas?

2020-10-01 10:18 UTC, merged