Add useReviews factory with tests
DivanteLtd/vue-storefront pull request #4830
Opened 2020-09-03 13:42 UTC by filipsobol

Adds `useReviewsFactory` with types and tests, closes #4775.

Additionally, I added `totalReviews` property in case there are more reviews than we're able to display at once (pagination).

2020-09-03 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=4830) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=4830) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vue-storefront?pullRequest=4830) it.</sub>

2020-09-04 13:12 UTC, andrzejewsky requested changes

2020-09-04 13:12 UTC, andrzejewsky commented on packages/core/core/src/factories/useReviewsFactory.ts
> +    const add = async (params: REVIEW_ADD_PARAMS): Promise<void> => {
addReview

2020-09-04 13:44 UTC, filrak approved these changes

2020-09-04 13:58 UTC, filrak commented
Please add to changelog ;)

2020-09-04 14:13 UTC, filipsobol commented
> Please add to changelog ;)

Done

2020-09-07 09:47 UTC, andrzejewsky approved these changes
@filipsobol missing interface for getters, but please do it in the next task

2020-09-07 09:48 UTC, merged