Integrate My Profile page
DivanteLtd/vue-storefront pull request #4939
Opened 2020-09-30 10:08 UTC by filipsobol

### Short Description and Why It's Useful
This PR integrates "Personal Data" and "Password Reset" forms in "My Profile" page with methods exposed by `useUser`.

Additionally it:
- Adds new `getEmailAddress` getter in `userGetters`,
- Makes checkbox `I want to create an account` required in registration form,
- Improves error flow, so they can be properly catched in the template and in the future, displayed nicely to use user.

### Upgrade Notes and Changelog
- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [X] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

2020-10-07 07:32 UTC, filrak requested changes
Nice job! Everything is much cleaner ;) I've added few DX-related suggestions

2020-10-07 07:32 UTC, filrak commented on packages/commercetools/composables/src/useUser/authenticate.ts
> +    console.error(err.message);
**change** use Logger

2020-10-07 07:32 UTC, filrak commented on packages/commercetools/theme/components/profile/PasswordResetForm.vue
> +<template>
**suggestion** In the project a convention is to name folders in `components` that group components specific to a certain page in a dir with a name of that page (eg `Checkout.vue` - page, `checkout` - dir in components) and other components either in a root or grouped if they're all about a specific feature. These components are part of `MyAccount` so lets rename that dir accordingly :)

2020-10-07 07:32 UTC, filrak commented on packages/commercetools/theme/components/profile/PasswordResetForm.vue
> +    const clearForm = () => ({
**question** isn't this implying that we're clearing the `form` not returning its default values?

2020-10-07 08:20 UTC, andrzejewsky approved these changes

2020-10-13 10:06 UTC, andrzejewsky approved these changes

2020-10-13 10:07 UTC, merged