GTM: update product mutation name to fix missing product details event
DivanteLtd/vue-storefront pull request #5033
Opened 2020-10-16 21:57 UTC by talalus

### Related Issues

closes #

### Short Description and Why It's Useful
Mutation type name has been changed from `SET_PRODUCT_CURRENT` to `SET_CURRENT` in product module so I changed the mutation name in GTM module to keep "Measuring Views of Product Details" event working.

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-10-16 21:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vue-storefront?pullRequest=5033) it.</sub>

2020-10-19 20:22 UTC, Fifciu requested changes
Good catch!
However, I would recommend to import `PRODUCT_SET_ORIGINAL` from this file and use `product/${PRODUCT_SET_ORIGINAL}`

2020-11-02 22:26 UTC, talalus commented
Hi @Fifciu 
names are now imported

2020-11-04 10:38 UTC, Fifciu approved these changes

2020-11-04 10:39 UTC, merged

2020-11-04 10:39 UTC, Fifciu commented
Great, thanks!