Wishlist with customQuery support
DivanteLtd/vue-storefront pull request #5060
Opened 2020-10-22 11:55 UTC by Fifciu

### Related Issues

closes #5059

### Short Description and Why It's Useful

Custom query support in Wishlist Factory

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

2020-10-22 12:05 UTC, andrzejewsky approved these changes

2020-10-22 12:23 UTC, lukasborawski requested changes

2020-10-22 12:23 UTC, lukasborawski commented on packages/core/core/src/types.ts
> +  loadWishlist(customQuery?: CustomQuery): Promise<void>;
I think you need overloading here:

```
loadWishlist(): Promise<void>;
loadWishlist(customQuery?: CustomQuery): Promise<void>;
```

2020-10-22 12:28 UTC, lukasborawski approved these changes

2020-10-22 13:05 UTC, filipsobol approved these changes

2020-10-23 10:23 UTC, filrak approved these changes

2020-10-23 10:23 UTC, merged