Allow array of localForage fallback drivers in config
DivanteLtd/vue-storefront pull request #5097
Opened 2020-10-29 11:06 UTC by didkan

### Short Description and Why It's Useful
Since implementing Sentry I have found a ton of errors such as `No available storage method found.`.
Researching those errors I found that `localForage` is only configured with one driver. This means that clients that don't support that one driver will not work with ´localForage´. The recommended config is using an array of drivers so that there are fallback drivers when the first one is not supported.

The current implementation in VSF does not allow for using an array in the `localForage` config, due to how `/core/lib/storage-manager.ts` is implemented.
This PR tries to fix that.

Before this fix the `localForage` config could look like this:
```
"localForage": {
  "defaultDrivers": {
    "elasticCache": "INDEXEDDB"
  }
}
```
After this fix we can use an array of fallback drivers like this:
```
"localForage": {
  "defaultDrivers": {
    "elasticCache": ["INDEXEDDB", "WEBSQL", "LOCALSTORAGE"]
  }
}
```

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-10-29 11:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5097) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5097) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vue-storefront?pullRequest=5097) it.</sub>

2020-10-30 08:55 UTC, gibkigonzo approved these changes

2020-10-30 09:02 UTC, Fifciu requested changes
Could you please write some simple doc about this PR? Without that, it could become one of the features that are useful for the community but developers do not even know about it.

2020-10-30 10:01 UTC, didkan commented
@Fifciu I have added docs now. Please, let me know if you want me to elaborate more. But now at least the feature is deocumented so it can be found.

2020-11-02 09:28 UTC, Fifciu approved these changes
Great job!

2020-11-02 09:28 UTC, merged