fix: updated UI version
DivanteLtd/vue-storefront pull request #6240
Opened 2021-08-26 10:06 UTC by justyna-13

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

#### Changelog
- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [ ] My code follows the code style of this project.

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-08-30 09:29 UTC, AdamPawlinski commented on packages/core/nuxt-theme-module/theme/pages/Category.vue
> +              @click:add-to-cart="addItemToCart({ product, quantity: Number(qty) })"
@igorwojciechowski  it's fixed, please take a look. I also fixed quantity value management in category, cause change quantity on one product caused also changing this value for other products.

2021-09-03 12:44 UTC, igorwojciechowski requested changes
Seems like clicking "Continue to Billing" after selecting shipping method does not trigger any action. Please verify.

2021-09-06 08:58 UTC, AdamPawlinski commented
@igorwojciechowski  button "Continue to Billing" fixed as long as other buttons which didn't work properly. Please check it.

2021-09-06 14:28 UTC, igorwojciechowski approved these changes

2021-09-20 13:18 UTC, merged